package org.khord.shared.crypto

import com.ionspin.kotlin.crypto.scalarmult.ScalarMultiplication
import com.ionspin.kotlin.crypto.signature.Signature

/**
 * Pre-key generation — X3DH §3.2.
 *
 * A "pre-key" is a Diffie-Hellman X25519 keypair Bob publishes on the Key
 * Server so Alice can initiate a session asynchronously without Bob being
 * online. There are two kinds:
 *
 *   * **Signed pre-key (SPK)** — medium lifetime (rotated periodically).
 *     The Ed25519 identity key signs `Encode(SPK_pub)` so Alice can verify
 *     that the SPK genuinely came from Bob.
 *   * **One-time pre-keys (OPKs)** — single-use, batched. Each consumed
 *     OPK contributes a fresh DH (DH4 in X3DH) and its private half is
 *     deleted after the X3DH that consumed it (X3DH §3.4).
 *
 * In Khord, X25519 keypairs are generated by sampling a 32-byte random
 * secret scalar and computing the public half via the X25519 base-point
 * multiplication. Sampling-then-multiply avoids allocating an Ed25519
 * intermediate that we'd then discard.
 */
@OptIn(ExperimentalUnsignedTypes::class)
internal object PreKeys {

    /**
     * Generate a fresh X25519 keypair via X25519 base-point multiplication.
     *
     *   sk = randombytes(32)
     *   pk = X25519(sk, basepoint)
     */
    fun generateX25519KeyPair(): X25519KeyPair {
        val sk = Random.bytes(32)
        val pk = ScalarMultiplication.scalarMultiplicationBase(sk.toUByteArray()).toByteArray()
        return X25519KeyPair(publicKey = pk, secretKey = sk)
    }

    /**
     * Generate a signed pre-key — X3DH §3.2.
     *
     * The signature is `Sig(IK_B, Encode(SPK_pub))` — Ed25519 detached over
     * the raw 32-byte X25519 public key bytes. This signature is what
     * Alice verifies before performing X3DH, ensuring the SPK genuinely
     * belongs to Bob (and not a malicious Key Server).
     *
     * `Encode(SPK)` per X3DH §2.4 is the curve25519 u-coordinate. Khord
     * uses the raw 32-byte public key bytes as Encode (no curve type
     * prefix), since both endpoints are X25519-only — there is no curve
     * polymorphism to disambiguate.
     */
    fun generateSignedPreKey(
        identity: IdentityKey,
        keyId: Int,
    ): SignedPreKey.Generated {
        val pair = generateX25519KeyPair()
        val signature = Signature.detached(
            pair.publicKey.toUByteArray(),
            identity.ed25519SecretKey.toUByteArray(),
        ).toByteArray()
        return SignedPreKey.Generated(
            signedPreKey = SignedPreKey(
                keyId = keyId,
                publicKey = pair.publicKey,
                signature = signature,
            ),
            secretKey = pair.secretKey,
        )
    }

    /**
     * Generate a batch of one-time pre-keys — X3DH §3.2.
     *
     * `keyIds` lets the caller assign arbitrary monotonic IDs (the server
     * never enforces a particular numbering — it just stores the IDs Bob
     * provides and returns them on fetch).
     */
    fun generateOneTimePreKeys(keyIds: IntRange): List<OneTimePreKey.Generated> {
        return keyIds.map { id ->
            val pair = generateX25519KeyPair()
            OneTimePreKey.Generated(
                oneTimePreKey = OneTimePreKey(keyId = id, publicKey = pair.publicKey),
                secretKey = pair.secretKey,
            )
        }
    }

    /**
     * Verify a signed pre-key signature — X3DH §3.3 step 1 / §4.5.
     *
     * Required: the signature MUST be verified before any DH operation.
     * Skipping this allows a malicious Key Server to substitute the SPK
     * (X3DH §4.5: "weak forward secrecy" attack).
     */
    fun verifySignedPreKey(
        signedPreKey: SignedPreKey,
        identityKeyEd25519Pub: ByteArray,
    ): Boolean {
        return try {
            Signature.verifyDetached(
                signedPreKey.signature.toUByteArray(),
                signedPreKey.publicKey.toUByteArray(),
                identityKeyEd25519Pub.toUByteArray(),
            )
            true
        } catch (e: Exception) {
            false
        }
    }
}
