#!/usr/bin/env bash
#
# Khord production setup — interactive bootstrap.
#
# Verifies prerequisites, prompts for the two domains, generates strong
# random secrets via `openssl rand`, writes a fresh .env, brings the stack
# up, waits for both services to report healthy, and prints a success
# summary.
#
# Run from repo root or from deploy/ — the script normalises its own cwd.

set -euo pipefail

# Move to deploy/ regardless of where we were invoked from.
cd "$(dirname "$0")/.."
DEPLOY_DIR="$(pwd)"
ENV_FILE="${DEPLOY_DIR}/.env"
COMPOSE_FILE="${DEPLOY_DIR}/docker-compose.prod.yml"

bold() { printf "\033[1m%s\033[0m\n" "$*"; }
err()  { printf "\033[31m✗ %s\033[0m\n" "$*" >&2; }
ok()   { printf "\033[32m✓ %s\033[0m\n" "$*"; }

# ── Prerequisite checks ──────────────────────────────────────────────────────

bold "Khord production setup"
echo

if ! command -v docker >/dev/null 2>&1; then
    err "docker not found. Install Docker first: https://docs.docker.com/engine/install/"
    exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
    err "docker compose plugin not available. Install docker-compose-v2."
    exit 1
fi
if ! command -v openssl >/dev/null 2>&1; then
    err "openssl not found. Required for secret generation."
    exit 1
fi
ok "Docker, Compose, openssl present"

# ── .env handling ────────────────────────────────────────────────────────────

if [[ -f "$ENV_FILE" ]]; then
    echo
    echo ".env already exists at $ENV_FILE"
    read -r -p "Overwrite it? [y/N] " ANS
    case "$ANS" in
        y|Y|yes|YES) ;;
        *) echo "Keeping existing .env. Skipping setup."; exit 0 ;;
    esac
fi

# ── Domains ──────────────────────────────────────────────────────────────────

echo
bold "Domains"
echo "Both must already resolve to this host (DNS A/AAAA record)."
echo "Caddy needs ports 80 + 443 open for Let's Encrypt to issue certs."
echo
read -r -p "Key server domain   (e.g. keys.example.com): "  DOMAIN_KEYSERVER
read -r -p "Relay server domain (e.g. relay.example.com): " DOMAIN_RELAY

if [[ -z "$DOMAIN_KEYSERVER" || -z "$DOMAIN_RELAY" ]]; then
    err "Both domains are required."
    exit 1
fi

# ── Secret generation ────────────────────────────────────────────────────────

KEY_SERVER_TOKEN_SECRET="$(openssl rand -hex 32)"
KEYSERVER_DB_PASSWORD="$(openssl rand -hex 24)"
RELAYSERVER_DB_PASSWORD="$(openssl rand -hex 24)"
ok "Generated KEY_SERVER_TOKEN_SECRET, KEYSERVER_DB_PASSWORD, RELAYSERVER_DB_PASSWORD"

# ── Write .env ───────────────────────────────────────────────────────────────

cat > "$ENV_FILE" <<EOF
# Generated by deploy/scripts/setup.sh on $(date -Iseconds).
# Do not commit. See .env.example for documentation.

DOMAIN_KEYSERVER=$DOMAIN_KEYSERVER
DOMAIN_RELAY=$DOMAIN_RELAY

KEY_SERVER_TOKEN_SECRET=$KEY_SERVER_TOKEN_SECRET
KEYSERVER_DB_PASSWORD=$KEYSERVER_DB_PASSWORD
RELAYSERVER_DB_PASSWORD=$RELAYSERVER_DB_PASSWORD

RELAY_PROOF_OF_WORK_DIFFICULTY_BITS=16
RELAY_MESSAGE_TTL_SECONDS=604800
EOF
chmod 600 "$ENV_FILE"
ok "Wrote $ENV_FILE (mode 600)"

# ── Bring the stack up ───────────────────────────────────────────────────────

echo
bold "Starting the stack"
docker compose -f "$COMPOSE_FILE" up -d --build

# ── Wait for health ──────────────────────────────────────────────────────────

echo
bold "Waiting for services to report healthy (up to ~3 minutes)…"

wait_healthy() {
    local svc="$1"
    local deadline=$((SECONDS + 180))
    while (( SECONDS < deadline )); do
        local status
        status="$(docker compose -f "$COMPOSE_FILE" ps --format json "$svc" \
            | grep -oE '"Health":"[^"]*"' | head -1 | sed 's/.*:"//;s/"//' || true)"
        case "$status" in
            healthy) ok "$svc healthy"; return 0 ;;
            unhealthy) err "$svc reported unhealthy. Check logs: docker compose -f deploy/docker-compose.prod.yml logs $svc"; return 1 ;;
            *) sleep 3 ;;
        esac
    done
    err "$svc did not become healthy within 180s. Check: docker compose -f deploy/docker-compose.prod.yml logs $svc"
    return 1
}

wait_healthy keyserver-db || exit 1
wait_healthy relayserver-db || exit 1
wait_healthy keyserver || exit 1
wait_healthy relayserver || exit 1

# Caddy doesn't have a built-in healthcheck (it's a reverse proxy with a
# different lifecycle); we just confirm the public TLS endpoints respond.
echo
bold "Checking public health endpoints"
sleep 5  # give Caddy a beat to obtain certs after upstreams come up
for url in "https://${DOMAIN_KEYSERVER}/v1/health" "https://${DOMAIN_RELAY}/v1/health"; do
    if curl -fsS --max-time 30 "$url" >/dev/null; then
        ok "$url"
    else
        err "$url did not respond. Cert issuance may still be in progress; retry in a minute."
    fi
done

# ── Summary ──────────────────────────────────────────────────────────────────

echo
bold "Setup complete."
cat <<EOF

Share these URLs with your Khord users — both go in the app's
"Use custom servers" screen at first launch:

    Key server:   https://${DOMAIN_KEYSERVER}
    Relay server: https://${DOMAIN_RELAY}

Stack is running in the background. Useful follow-ups:

    docker compose -f deploy/docker-compose.prod.yml ps
    docker compose -f deploy/docker-compose.prod.yml logs -f
    deploy/scripts/backup.sh          # snapshot both databases

EOF
